### ISSUE TITLE
New Silva138 gives wrong taxa when adding greengenes prefix

### ISSUE THREAD

**Issue by currocam** [AU-ENVS-Bioinformatics/TotalRNA-Snakemake#16]
## Case 1
What we got: 
k__Archaeplastida; p__Chlorophyta; c__Chlorophyceae; o__Chlamydomonadales; f__Chlamydomonadales XX; g__; s__
What's wrong:
Chlamydomonadales is not a family name

## Case 2
What we got: 
k__Archaeplastida; p__Embryophyta; c__Liliopsida; o__Poales; f__Poaceae; g__Triticeae; s__Hordeum
What's wrong:
because of the double family level (-ceae), all is shifted by 1, which you can see because Hordeum is a genus, not species

## Case 3
What we got:
k__Archaeplastida; p__Embryophyta; c__Pinophyta; o__; f__; g__; s__
What's wrong:
phyto = phylum, so Pinophyta likely also redundant

**Comment by MaSchCodes** [comment]
This is related to the CREST 4 manual edits of the SILVA 138 database, resulting in some faulty or redundant labels:
root; Main genome; Eukaryota; Amorphea; Choanoflagellida; Choanoflagellida (phylum); Choanoflagellida X; Choanoflagellida XX
--> here X replicates the former taxonomic level, but instead should be omitted as level
